{% set name = "libobjcryst" %}
{% set version = "2021.1.2" %}
{% set sha256 = "7f4d2c7e42154bbc780032ce7efe303b57a14d566b9b52fad8c6754a53b1365d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/diffpy/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('libobjcryst', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - scons
  host:
    - boost

test:
  commands:
    - test -f $PREFIX/lib/libObjCryst${SHLIB_EXT}

about:
  home: https://github.com/diffpy/libobjcryst/
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE.txt
  summary: ObjCryst++ packaged for installation as a shared library.

  description: |
    ObjCryst++ is Object-Oriented Crystallographic Library for C++ developed
    by Vincent Favre-Nicolin. libobjcryst is a mirror of the ObjCryst++
    sources from https://sourceforge.net/projects/objcryst, expanded with
    SCons build scripts to make it easier to install as a system shared
    library. libobjcryst does not include GUI related files from ObjCryst++.
    This distribution contains required sources from cctbx and newmat that are
    used in ObjCryst++.
  doc_url: https://github.com/diffpy/libobjcryst
  dev_url: https://github.com/diffpy/libobjcryst

extra:
  recipe-maintainers:
    - vincefn
    - pavoljuhas
    - sbillinge
    - st3107
