# Customize scons build environment.
import os
import sys

# add variable env
env = Environment(ENV = {'PATH' : os.environ['PATH']})
env.SConscript(dirs=['mydir'], exports='env')

# Apply environment settings for Anaconda compilers
env.Replace(CXX=os.environ['CXX'])
env.MergeFlags(os.environ['CFLAGS'])
env.MergeFlags(os.environ['CPPFLAGS'])
env.MergeFlags(os.environ['CXXFLAGS'])
env.MergeFlags(os.environ['LDFLAGS'])

# Use the default c++98 language standard
cxxflags98 = [f for f in env['CXXFLAGS'] if not f.startswith('-std=')]
env.Replace(CXXFLAGS=cxxflags98)

# vim: ft=python
